---

- name: Install InfluxDB (Console)
  package:
    name="https://s3.amazonaws.com/influx-enterprise/releases/influx-enterprise-{{ influxdb_version }}.x86_64.rpm"
    state="present"

- name: Install InfluxDB Config (Console)
  template:
    src="influxdb-enterprise.conf.j2"
    dest="/etc/influx-enterprise/influx-enterprise.conf"
    owner="{{ influxdb_unix_user }}"
    group="{{ influxdb_unix_group }}"
    mode="0600"
