---

- name: Install InfluxDB (Console)
  package:
    name="{{ influxdb_console_dl_baseurl }}/influx-enterprise-{{ influxdb_version }}.x86_64.rpm"
    state="present"

- name: Install InfluxDB Config (Console)
  template:
    src="influxdb-enterprise.conf.j2"
    dest="/etc/influx-enterprise/influx-enterprise.conf"
    owner="{{ influxdb_enterprise_unix_user }}"
    group="{{ influxdb_enterprise_unix_group }}"
    mode="0600"

- name: Setup the SQLLite DB (Console)
  command: >
    influx-enterprise migrate
    --config /etc/influx-enterprise/influx-enterprise.conf
  when: "'sqllite' in influxdb_database_url"

- name: Fix Perms on SQLLite (Console)
  file:
    path="/var/lib/influx-enterprise"
    owner="{{ influxdb_enterprise_unix_user }}"
    group="{{ influxdb_enterprise_unix_group }}"
    recursive=true
  when: "'sqllite' in influxdb_database_url"

- name: Restart Console
  command: /bin/true
  notify: restart influx-enterprise
