---

- name: Install InfluxDB (Console)
  package:
    name="{{ influxdb_console_dl_baseurl }}/influx-enterprise-{{ influxdb_console_version }}.x86_64.rpm"
    state="present"

- name: Install InfluxDB Config (Console)
  template:
    src="influxdb-enterprise.conf.j2"
    dest="/etc/influx-enterprise/influx-enterprise.conf"
    owner="{{ influxdb_enterprise_unix_user }}"
    group="{{ influxdb_enterprise_unix_group }}"
    mode="0600"

- name: Setup the SQLLite DB (Console)
  command: >
    influx-enterprise migrate
    --config /etc/influx-enterprise/influx-enterprise.conf
  when: "'sqllite' in influxdb_database_url"
  become: true
  become_user: "{{ influxdb_enterprise_unix_user }}"

- name: Ouput InfluxDB License File
  copy:
    content="{{ influxdb_enterprise_license_file_contents | to_nice_json }}"
    dest="{{ influxdb_enterprise_console_license_path }}"
    owner="{{ influxdb_enterprise_unix_user }}"
    group="{{ influxdb_enterprise_unix_group }}"
    mode="0600"
  when:
    - influxdb_enterprise_license_file_contents != ""
    - influxdb_enterprise_license_path != ""

- name: Restart Console
  command: /bin/true
  notify: restart influx-enterprise
