---

- name: Install InfluxDB (Data)
  package:
    name="{{ influxdb_dl_baseurl }}/influxdb-data-{{ influxdb_version }}_c{{ influxdb_subversion }}.x86_64.rpm"
    state="present"
  register: influxdb_data_package

- name: Install InfluxDB Config (Data)
  template:
    src="influxdb.conf.j2"
    dest="/etc/influxdb/influxdb.conf"
    owner="{{ influxdb_unix_user }}"
    group="{{ influxdb_unix_group }}"
    backup="yes"
    mode="0600"
  register: influxdb_data_config

- name: Ouput InfluxDB License File
  copy:
    content="{{ influxdb_enterprise_license_file_contents | to_nice_json }}"
    dest="{{ influxdb_enterprise_license_path }}"
    owner="{{ influxdb_unix_user }}"
    group="{{ influxdb_unix_group }}"
    backup="yes"
    mode="0600"
  when:
    - influxdb_enterprise_license_file_contents != ""
    - influxdb_enterprise_license_path != ""

- name: Restart Data
  command: /bin/true
  when: influxdb_data_config.changed or influxdb_data_package.changed
  notify: restart influxdb
