---

- name: Install InfluxDB (Data)
  package:
    name="{{ influxdb_dl_baseurl }}/influxdb-data-{{ influxdb_version }}_c{{ influxdb_subversion }}.x86_64.rpm"
    state="present"

- name: Install InfluxDB Config (Data)
  template:
    src="influxdb.conf.j2"
    dest="/etc/influxdb/influxdb.conf"
    owner="{{ influxdb_unix_user }}"
    group="{{ influxdb_unix_group }}"
    mode="0600"

- name: Ouput InfluxDB License File
  copy:
    content="{{ influxdb_enterprise_license_file_contents | to_nice_json }}"
    dest="{{ influxdb_enterprise_license_path }}"
    owner="{{ influxdb_unix_user }}"
    group="{{ influxdb_unix_group }}"
    mode="0600"
  when:
    - influxdb_enterprise_license_file_contents != ""
    - influxdb_enterprise_license_path != ""
