---

- name: Install Kapacitor
  package:
    name="{{ kapacitor_dl_baseurl }}/kapacitor-{{ kapacitor_version }}.x86_64.rpm"
    state=present
  register: influxdb_kapacitor_package

- name: Install Kapacitor Config
  template:
    src="kapacitor.conf.j2"
    dest="/etc/kapacitor/kapacitor.conf"
    owner="{{ kapacitor_unix_user }}"
    group="{{ kapacitor_unix_group }}"
    backup="yes"
    mode="0600"
  register: influxdb_kapacitor_config

- name: Restart Kapacitor
  command: /bin/true
  notify: restart kapacitor
  when: influxdb_kapacitor_config.changed or influxdb_kapacitor_package.changed
