---

- name: Check Key Contents OR Key
  fail:
    msg="You can only specify one of license key file contents OR license key itself"
  when:
    - influxdb_enterprise_license_file_contents != ""
    - influxdb_enterprise_license_key != ""

- name: Import InfluxDB GPG Key
  rpm_key:
    key="https://repos.influxdata.com/influxdb.key"
    state="present"

- name: Install InfluxDB Meta
  include: meta.yml
  when: influxdb_is_meta

- name: Install InfluxDB Data
  include: data.yml
  when: influxdb_is_data

- name: Install InfluxDB Console
  include: console.yml
  when: influxdb_is_console

- name: Install InfluxDB Kapacitor
  include: kapacitor.yml
  when: influxdb_is_kapacitor
